- src/core/scroller.ts
- src/core/store.ts
- src/react/List.tsx
- stories/basics/List.stories.tsx
> Add scrollOffset, scrollSize and scrollToOffset to handle

- stories/comparisons/comparisons.stories.tsx
- stories/comparisons/components/react-cool-virtual.tsx
- stories/comparisons/components/react-virtual.tsx
- stories/comparisons/components/react-virtualized.tsx
- stories/comparisons/components/react-virtuoso.tsx
- stories/comparisons/components/react-window.tsx
- stories/comparisons/components/virtua.tsx
- stories/comparisons/for benchmarks/react-cool-virtual.stories.tsx
- stories/comparisons/for benchmarks/react-virtual.stories.tsx
- stories/comparisons/for benchmarks/react-virtualized.stories.tsx
- stories/comparisons/for benchmarks/react-virtuoso.stories.tsx
- stories/comparisons/for benchmarks/react-window.stories.tsx
- stories/comparisons/for benchmarks/virtua.stories.tsx
#65 
Some optimization for layout recalculation done in virtua and react-virtualized seems to be disabled with `display: flex`.
So I fixed some style to enable them for now.
> Remove flex from some stories for benchmarking

- src/core/store.ts
- src/react/VList.spec.tsx
- src/react/VList.tsx
When children's length was changed, currently virtua renders twice but this behavior confused animation libraries like framer motion.
This PR will remove the rerender. 
NOTE:
Updating state in render is ok in React, but it can't be used with useSyncExternalStore because it causes `Warining: Cannot update a component (VList) while rendering a different component (VList).`...
It might be a simlar issue to https://github.com/urql-graphql/urql/issues/1382 .
> Remove rerender when cache length is updated

- src/react/VGrid.tsx
- stories/basics/VGrid.stories.tsx
> Implement handle of VGrid

- src/react/WVList.tsx
WVList is controlled by window scrolling so we can just use `window.addEventListener('scroll', fn)`.
> Remove onScroll prop from WVList

- src/core/utils.ts
https://stackoverflow.com/questions/56245578/why-is-array-froms-callback-much-slower-than-the-map-function
https://dev.to/henryjw/array-map-much-slower-than-for-loop-57if
> Optimize range

- src/core/scroller.ts
- src/core/store.ts
- src/react/VGrid.tsx
- src/react/VList.tsx
- src/react/WVList.tsx
- src/react/useSelector.ts
> Select scrolling state from store

- src/index.ts
- src/react/VGrid.spec.tsx
- src/react/VGrid.tsx
- src/react/VList.spec.tsx
- src/react/VList.tsx
- src/react/Viewport.tsx
- src/react/WVList.spec.tsx
- src/react/WVList.tsx
- src/react/index.ts
- src/react/utils.ts
- stories/advanced/PullToRefresh.stories.tsx
- stories/advanced/Table.stories.tsx
- stories/advanced/With react-select.stories.tsx
- stories/advanced/Zoomable.stories.tsx
- stories/basics/VList.stories.tsx
- element -> components.Root
- itemElement -> components.Item
- CustomWindowComponent -> CustomViewportComponent
> Rename element props to components

- e2e/VList.spec.ts
- src/core/scroller.ts
- src/core/store.ts
- src/core/types.ts
- src/index.ts
- src/react/VList.tsx
- stories/advanced/Chat.stories.tsx
- stories/basics/VList.stories.tsx
> Add align option to scrollToIndex method

- stories/basics/VList.stories.tsx
Hey cool package :)
I've come across a bug; going from `some children` to `no children` then back to `some children` throws a React `Too many re-renders` on the `VList` component
To demonstrate I added the option of "decrease" to the `IncreasingItems` storybook example, so you can easily reproduce. But I haven't got time to delve much deeper
An easy workaround for anyone else encountering this is to skip rendering the `VList` when you know your children array is empty
> Add decreasing storybook example

- e2e/VList.spec.ts
- src/core/scroller.ts
- src/react/VGrid.tsx
- src/react/VList.spec.tsx
- src/react/VList.tsx
- stories/basics/VList.stories.tsx
#175 
[As described in mdn](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollHeight#determine_if_an_element_has_been_totally_scrolled), `scrollHeight` is rounded number but `scrollTop` and `contentRect` from ResizeObserver has non-rounded number.
Because of this difference, scrollSize which is used internally in this lib (calcurated from `contentRect`) and scrollSize what users can get from handle (`scrollHeight`) can have different value if browser's `window.devicePixelRatio` has decimal value (ex. `1.5` or `1.25` in Windows OS). That makes it harder to implement at-bottom detection logic in userland.
So this PR will replace scrollHeight usages with stored scrollSize. scrollHeight was necessary in scrollToIndex of early implementation but it seems that it's not now.
> Replace scrollHeight/scrollWidth with stored scrollSize

- .size-limit.json
- src/core/scroller.ts
- src/core/store.ts
- src/react/VGrid.tsx
- src/react/VList.tsx
- src/react/WVList.tsx
- src/react/utils.ts
> Prerender items longer for scroll direction

- src/core/store.ts
- stories/advanced/Feed.stories.tsx
#206
#162 
This PR will change jump compensation logic to maintain visible position always (except pre-measuring for imperative scrolling).
This fix was made possible by improvement in  #199.
> Change jump compensation logic to maintain visible position always

- .size-limit.json
- src/core/scroller.ts
fix #211 
https://github.com/prud/ios-overflow-scroll-to-top
https://jsfiddle.net/prud/umr0qegs/
> Fix glitch caused by second touch while momentum scrolling in iOS Safari

- .size-limit.json
- src/core/resizer.ts
- src/core/scroller.ts
- src/core/store.ts
> Include padding in calculation of scrollToIndex destination

- e2e/VList.spec.ts
- e2e/utils.ts
- src/core/scroller.ts
- src/core/store.ts
fix #14 
fix #221 
This PR will change smooth scrolling algorithm to mount all items between start and end for measuring before scrolling.
It may sound that it affects performance, but it will not have much difference because almost all items between start and end will be mounted during smooth scrolling even if we didn't do it manually.
> Improve smoothness of smooth scrolling

- src/core/scroller.ts
fix #231 
This PR removes optimization with visibility in WVList.
Scroll event may fires on navigation when history.scrollRestoration is 'auto'. However it may be or may not be before first IntersectionObserver call, so it was unstable.
> Fix bug scroll restoration of browser sometimes does not work on WVList

- .size-limit.json
- .storybook/preview.jsx
- README.md
- src/react/index.ts
- stories/basics/VGrid.stories.tsx
#124 
List virtualization is stable enough and battle tested, but grid virtualization is not yet.
And I've noticed grid virtualization has different usecases from list, like spread sheet or masonry grid. I want to change VGrid drastically to support them.
So rename it for clarification.
> Rename VGrid to experimental_VGrid

- src/core/store.ts
- src/react/WVList.tsx
- stories/basics/WVList.stories.tsx
**Bug**
Items aren't displayed properly when all of the following conditions are met.
- passing cache props to WVList and exists cache.
-  both the current page scrollY and the previous page scrollY are 0, and the scroll action registered in eventListener does not be called.
**To Reproduce**
[demo on stackblitz.com](https://stackblitz.com/edit/virtua-scroll-restoration-nhynzv?file=package.json,src%2Fmain.tsx,src%2FApp.tsx&terminal=dev)
1. Check Passing cache props to WVList.
2. Move from the document which isn't scrolled at all up or down (scrollY is 0) to the WVList document which isn't too (scrollY is 0). 
3. WVList displayed only a few items.
**Platform:**
- OS: Windows
- Browser: Chrome
- Version of react: 18.2.0
- Version of this package: 0.15.7
**Bug fix**
I don't know what is the …
> fix: WVList scroll restoration bug and add storybook example.

- .storybook/preview.jsx
- e2e/VList.ios.spec.ts
- e2e/utils.ts
- playwright.config.ts
> Enable e2e for Mobile Safari

- src/core/store.ts
- stories/advanced/Feed.stories.tsx
- stories/basics/VList.stories.tsx
> Improve jump compensation immediately after prepending

- src/core/store.ts
- src/react/VGrid.tsx
- src/react/VList.tsx
- src/react/WVList.tsx
Scroll direcion detection was improved in #255. However it also made onScrollStop unstable after imperative scrolling.
This PR changes onScrollStop to subscribe the store similar to onScroll, to make it more reliable.
> Fix bug that onScrollStop may not be called after imperative scrolling

- src/core/scroller.ts
- src/core/utils.ts
> Improve touch handling in WindowVirtualizer

- src/core/store.ts
> Refactor calculateJump

- e2e/VList.spec.ts
- e2e/utils.ts
- src/core/scroller.ts
- src/core/store.ts
- stories/react/advanced/Chat.stories.tsx
> Cancel scheduled imperative scrolling when prepended

- src/core/cache.spec.ts
- src/core/cache.ts
- src/core/store.ts
fix #371 
fix #15 
The previous logic didn't work correctly with reverse scrolling, but it's now fixed.
> Improve automatic item size estimation

- .storybook/main.js
- package-lock.json
- package.json
- rollup.config.mjs
- scripts/babel-plugin-annotate-vue-vnode.mjs
- src/vue/ListItem.tsx
- src/vue/Virtualizer.tsx
- src/vue/WindowVirtualizer.tsx
#347 
https://github.com/vuejs/babel-plugin-jsx
https://github.com/vuejs/core/blob/main/packages/shared/src/patchFlags.ts
> Optimize Vue Virtualizer with @vue/babel-plugin-jsx

- src/core/store.ts
> Improve jump compensation and change minimum overscan to 0

- stories/react/advanced/Collapse nested.stories.tsx
https://github.com/inokawa/virtua/issues/385
> Add collapse nested storybook example

- src/react/Virtualizer.tsx
- src/solid/Virtualizer.tsx
- src/vue/VList.tsx
- src/vue/Virtualizer.tsx
> Add getItemOffset to VirtualizerHandle

- src/core/cache.spec.ts
- src/core/cache.ts
- src/core/store.ts
- src/core/types.ts
Removed some fields from snapshot because they are restorable from item sizes.
> Fix CacheSnapshot structure and reduce its size

- src/core/store.ts
- src/react/Virtualizer.tsx
- src/vue/Virtualizer.tsx
- stories/react/basics/Virtualizer.stories.tsx
- stories/vue/HeaderAndFooter.vue
> Suppress rerendering of WindowVirtualizer outside of viewport

- src/solid/RangedFor.tsx
- src/solid/Virtualizer.tsx
- src/solid/WindowVirtualizer.tsx
fix #425 
The reactivity seems to break inside the `RangedFor` component. 
With this change each item is passed as a function instead of as a value to the render function, which seems to fix the problem, without having to change the api of the library. I sadly don't know enough about solid to find out why passing it as a value is not working. 
To fix the reactivity when using `createStore` instead of `createSignal`, like in the following example: 
```
const App: Component = () => {
const [data, setData] = createStore(Array.from({ length: 100000 }, (v, i) => i));
return (
<>
<button onClick={() => {
setData(10, prev => prev * 2)
}}>
Update data
</button>
<VList data={data} style={{ height: "800px" }}>
{(item, i) => (
<div>
{item}
</div>
)}
</VList>
</>
);
}
```
The `untrack()` call inside …
> Fix solid reactivity

- src/react/VList.tsx
- src/react/Virtualizer.tsx
- stories/react/advanced/Keep offscreen items mounted.stories.tsx
fix #181 
This simple change fixes a number of issues with off-screen elements:
- audio/video stops playing
- issue with text input focus I mentioned in this discussion https://github.com/inokawa/virtua/discussions/414
- text input loses its state
But I'm guessing you wanted to find a generic solution that covers more use cases, right?
This seems to solve the most critical issues for me. The new prop could be added with `unstable_` or `experimental_` prefix, until you find a better solution, what do you think?
> Add ability to keep offscreen items mounted

- src/react/Virtualizer.tsx
Turned out that incorrect items order may cause some issues. And it cannot be fixed by sorting indexes on the user side, because `unshift` will break their order anyway.
In my case it was an embedded YouTube video that would autoplay multiple times in some conditions. Seems like the wrong items order caused react to re-create DOM elements.
> Fix off-screen items order

- src/core/cache.spec.ts
- src/core/cache.ts
- src/react/Virtualizer.tsx
- src/react/WindowVirtualizer.tsx
> Fallback to default cache if specified cache is shorter/longer

- src/core/store.ts
- src/react/Virtualizer.tsx
- src/vue/Virtualizer.tsx
> Support dynamic startMargin

- src/vue/ListItem.tsx
- src/vue/Virtualizer.tsx
- src/vue/WindowVirtualizer.tsx
> Add as and item props to Vue Virtualizer

- src/core/scroller.ts
- src/core/store.ts
> Improve timeout handling on imperative scroll when document is inactive

- src/react/types.ts
- src/solid/types.ts
Updates `ViewportComponentAttributes` to expose `onWheel` in `VList`.
Enables user to differentiate automated scroll behaviour from mouse scroll.
Solves problem from [this discussion](https://github.com/inokawa/virtua/discussions/486#discussioncomment-10278043).
> add onWheel to VList

- src/svelte/ListItem.svelte
- src/svelte/VList.svelte
- src/svelte/Virtualizer.svelte
- src/svelte/core.ts
- src/svelte/index.ts
- stories/svelte/HeaderAndFooter.svelte
- stories/svelte/Nested.svelte
- stories/svelte/TableElement.svelte
- stories/svelte/Virtualizer.stories.tsx
> Add Svelte Virtualizer

- src/react/Virtualizer.tsx
- src/solid/Virtualizer.tsx
- src/svelte/VList.svelte
- src/svelte/Virtualizer.svelte
- src/svelte/Virtualizer.type.ts
- src/svelte/core.ts
- src/vue/VList.tsx
- src/vue/Virtualizer.tsx
Exposing `getItemSize` to the `VirtualizerHandle`.
This will enable users to create their own `scrollToIndex` behavior as discussed in #538
> Add `getItemSize` to `VirtualizerHandle`

- src/core/scroller.ts
- src/core/store.ts
- src/react/VGrid.tsx
- src/react/VList.tsx
- src/react/Virtualizer.tsx
- src/react/WindowVirtualizer.tsx
- src/solid/VList.tsx
- src/solid/Virtualizer.tsx
- src/solid/WindowVirtualizer.tsx
- src/solid/index.ts
- src/svelte/VList.svelte
- src/svelte/VList.type.ts
- src/svelte/Virtualizer.svelte
- src/svelte/Virtualizer.type.ts
- src/svelte/WindowVirtualizer.svelte
- src/svelte/WindowVirtualizer.type.ts
- src/svelte/core.ts
- src/vue/VList.tsx
- src/vue/Virtualizer.tsx
- src/vue/WindowVirtualizer.tsx
- stories/react/advanced/Feed.stories.tsx
- stories/react/advanced/Sticky Group.stories.tsx
- stories/react/basics/VList.stories.tsx
- stories/react/basics/Virtualizer.stories.tsx
- stories/react/basics/WindowVirtualizer.stories.tsx
#378 
This PR removes `onRangeChange` prop because it is an obstacle to achieving #378 . 
Instead, this PR adds `startIndex`/`endIndex` getter to handles and `onScroll` to WindowVirtualizer, that opens more flexible configuration.
> Replace onRangeChange with handle methods

- rollup.config.mjs
fix #549 
```
runtime.js:5937 [Vue warn]: Invalid prop name: "$" is a reserved property. 
at <Anonymous ref=Ref< undefined > data= (1000) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, …]
```
> Fix error in Vue bundle after 0.37.0

- eslint.config.mjs
- src/core/index.ts
- src/core/utils.ts
- src/react/ListItem.tsx
- src/react/VGrid.tsx
- src/react/VList.tsx
- src/react/Virtualizer.tsx
- src/react/WindowVirtualizer.tsx
- src/react/useIsomorphicLayoutEffect.ts
- src/react/useRerender.ts
- src/react/utils.ts
- src/solid/ListItem.tsx
- src/solid/RangedFor.tsx
- src/solid/Virtualizer.tsx
- src/solid/WindowVirtualizer.tsx
- src/solid/utils.ts
- src/svelte/Virtualizer.type.ts
- src/svelte/WindowVirtualizer.type.ts
- src/svelte/core.ts
- src/svelte/utils.ts
- src/vue/ListItem.tsx
- src/vue/Virtualizer.tsx
- src/vue/WindowVirtualizer.tsx
- src/vue/utils.ts
> Organize core imports

- README.md
- src/svelte/VList.svelte
- src/svelte/WindowVirtualizer.svelte
- stories/svelte/Controls.svelte
- stories/svelte/Default.svelte
- stories/svelte/HeaderAndFooter.svelte
- stories/svelte/Horizontal.svelte
- stories/svelte/Nested.svelte
- stories/svelte/TableElement.svelte
- stories/svelte/WindowVirtualizer.svelte
The PR includes a minor refactor, moving towards a less verbose syntax, that is idiomatic to Svelte.
To share references regarding the syntax, the last code block in this tutorial link: https://svelte.dev/tutorial/svelte/dynamic-attributes, or the code blocks shown in this tutorial link: https://svelte.dev/tutorial/svelte/classes, could serve as examples.
> Use idiomatic svelte syntax for setting attribute values

- src/core/store.ts
fix #557 
It seems that Vue/Solid/Svelte batch rendering on update so just update state, for consistency.
> Fix reactivity issue on length change in Vue/Solid/Svelte

- src/vue/ListItem.tsx
- src/vue/VList.tsx
- src/vue/Virtualizer.tsx
- src/vue/utils.ts
- stories/vue/StickyGroup.vue
- stories/vue/VList.stories.ts
I wanted to use virtua for the usecase of sticky groups + virtualized scrolls in Vue but found that the APIs for that is not yet there.
I have added `keepMounted` from the React API and an additional `itemProps` to facilitate the Sticky Groups in Vue.
I have also added a story for the same.
If the PR is okay in its direction, I can add some documentation as well if needed.
> Add keepMounted and itemProps to Vue API to enable sticky groups

- src/react/WindowVirtualizer.tsx
- src/solid/WindowVirtualizer.tsx
- src/svelte/WindowVirtualizer.svelte
- src/svelte/WindowVirtualizer.type.ts
- src/vue/WindowVirtualizer.tsx
https://github.com/inokawa/virtua/discussions/580
> Remove offset argument of onScroll prop from WindowVirtualizer

- e2e/VList.spec.ts
- src/core/store.ts
- stories/react/advanced/SSR.stories.tsx
Here are the before and after results for this PR:
| Before | After |
|-------------------------------------------|-------------------------------------------|
| https://github.com/user-attachments/assets/1f9007b2-24f6-4fad-9051-0aa920d0ee81 | https://github.com/user-attachments/assets/f645f858-113f-43dc-b281-a43b0612fc8e |
I have updated the SSR story in the storybook to include this example. It has been added as a selectable checkbox.
Closes #590.
> Fix smooth scroll to index on SSR hydration

- e2e/VList.spec.ts
- e2e/Virtualizer.spec.ts
- e2e/WindowVirtualizer.spec.ts
- e2e/utils.ts
Unnecessary await was used on non-async functions and detected by typescript via lsp.
> Remove unnecessary awaits and variables from tests

- src/react/VGrid.tsx
fixes #658
seems that there is no vue/solid/svelte equivalent for VGrid and no tests for these ref methods, so all that's really needed is just to add them.
> add more methods to VGridHandle

- src/solid/Virtualizer.tsx
- src/solid/WindowVirtualizer.tsx
Prevents a race condition (when shift=true + prepend) when `dataSlice()` is called before `ACTION_ITEMS_LENGTH_CHANGE` is called, but with an updated list.
This leads to unnecessary renderings, because a new list with an old range() results in an incorrect list, which does not contain items from the current viewport.
> SolidJS: move ACTION_ITEMS_LENGTH_CHANGE to dataSlice memo

- .size-limit.json
- src/core/resizer.ts
- src/react/VGrid.tsx
- src/react/index.ts
- stories/react/basics/VGrid.stories.tsx
fixes #668 
- add `VGridHandle.resize(cols, rows)` method and `resizer.$resetAfter(row, col)` method to support it
- add a story that demonstrates resizing one row or column, or randomizing all of them
- open to feedback on the API here! I went through a bunch of iterations locally and this is the first that seemed to really work robustly in the ways I wanted it to.
> feat(react): VGrid supports resizing rows/cols
