src/react/List.tsx, src/react/useEvent.ts
=> Add onScrollStop prop

src/core/scroller.ts, src/react/List.tsx, stories/advanced/ScrollSync.stories.tsx
=> Add onScroll prop

src/react/List.tsx, stories/advanced/InfiniteScrolling.stories.tsx
=> Replace onEndReached and endThreshold with onRangeChange

src/react/List.tsx, stories/advanced/ScrollSync.stories.tsx, stories/basics/List.stories.tsx
=> Rename scrollToOffset to scrollTo and add scrollBy

package-lock.json, package.json, rollup.config.mjs, src/core/store.ts, src/react/VList.tsx, src/react/useStore.ts, src/react/useSyncExternalStore.ts
=> Replace useSyncExternalStore with useState

src/react/VList.tsx, src/react/useStore.ts
=> Cancel subscription if items are offscreen

e2e/list.spec.ts, src/core/scroller.ts, src/core/store.ts, src/react/VList.tsx
=> Defer applying jump to scroll position while scrolling

src/core/scroller.ts, src/core/store.ts
=> Discard scroll jump in some cases

e2e/list.spec.ts, src/core/scroller.ts, src/core/store.ts, src/react/VList.tsx
=> Revert pending jump

src/core/resizer.ts, src/core/scroller.ts
=> Separate ResizeObserver from scroller

src/core/store.ts, src/index.ts, src/react/VGrid.tsx, src/react/VList.tsx, stories/advanced/Chat.stories.tsx, stories/basics/VList.stories.tsx
=> Add reverse mode

package-lock.json, package.json, rollup.config.mjs
close #78 
https://github.com/rollup/rollup/issues/4699
=> Add `"use client"` to bundle for React Server Components support

e2e/grid.spec.ts, e2e/utils.ts, src/core/scroller.ts, src/core/store.ts, src/react/VGrid.tsx, src/react/VList.tsx
=> Refactor jump

src/core/cache.spec.ts, src/core/cache.ts, src/core/store.ts, src/core/utils.ts, src/react/VList.tsx, src/react/__snapshots__/VList.spec.tsx.snap, stories/advanced/InfiniteScrolling.stories.tsx, stories/advanced/Loop.stories.tsx, stories/basics/VList.stories.tsx
=> Estimate initial item size from measured sizes

src/core/store.ts, src/react/VGrid.tsx, src/react/VList.tsx
This logic was unintendedly excluded in #88 .
=> Fix viewport size if items are a few in reverse mode

e2e/WVList.spec.ts, e2e/utils.ts, stories/basics/WVList.stories.tsx
=> Add e2e for WVList

src/core/store.ts
=> Fix threshold for subpixels

src/core/cache.spec.ts, src/core/cache.ts, src/core/utils.ts
=> Unuse range

src/core/cache.ts, src/core/store.ts
=> Refactor resetCache

src/react/VList.tsx, src/react/WVList.tsx, stories/basics/VList.stories.tsx, stories/basics/WVList.stories.tsx, stories/basics/components.tsx
Remove count because it is substitutable.
=> Change argument of onRangeChange

src/core/cache.ts
https://v8.dev/blog/elements-kinds
=> Optimize updateCache

e2e/VList.spec.ts, src/core/cache.spec.ts, src/core/cache.ts, stories/basics/VList.stories.tsx
=> Fix infinite re-render when children increased after its length became 0

src/react/useSelector.ts
https://github.com/inokawa/virtua/issues/175#issuecomment-1715667352
=> Fix useLayoutEffect warn in SSR

e2e/VGrid.spec.ts, src/core/store.ts, src/react/ListItem.tsx, src/react/VGrid.tsx, src/react/VList.tsx, src/react/WVList.tsx, src/react/useSelector.ts
=> Batch flushSync updates

src/core/store.ts, stories/advanced/Chat.stories.tsx
=> Improve jump compensation in imperative scrolling

.size-limit.json, src/core/scroller.ts, src/core/store.ts, src/react/VGrid.tsx, src/react/VList.tsx, src/react/WVList.tsx, src/react/utils.ts
This reverts commit 860e22613b3aba0e82382848449af6c30b0f4179.
Revert breaking change for next release.
=> Revert "Prerender items longer for scroll direction"

.size-limit.json, src/core/scroller.ts, src/core/store.ts, src/react/VGrid.tsx, src/react/VList.tsx, src/react/WVList.tsx, src/react/utils.ts
This reverts commit d011b3fe9ed6552ba67280566a789c2a00cd73bc, reversing changes made to 3ac54adb72bab328688ed6e0f8d289d75adf9c12.
=> Revert "Merge pull request #189 from inokawa/revert-overscan"

.storybook/preview.jsx, e2e/VList.spec.ts, package.json, src/core/environment.ts, src/core/scroller.ts, src/react/ListItem.tsx, src/react/VGrid.rtl.spec.tsx, src/react/VGrid.tsx, src/react/VList.rtl.spec.tsx, src/react/VList.spec.tsx, src/react/VList.tsx, src/react/WVList.rtl.spec.tsx, src/react/WVList.tsx, src/react/__snapshots__/VGrid.rtl.spec.tsx.snap, src/react/__snapshots__/VList.rtl.spec.tsx.snap, src/react/__snapshots__/VList.spec.tsx.snap, src/react/__snapshots__/WVList.rtl.spec.tsx.snap, src/react/index.ts, src/react/useIsomorphicLayoutEffect.ts, stories/advanced/Chat.stories.tsx, stories/basics/VList.stories.tsx
=> Detect rtl style automatically

src/core/scroller.ts
=> Support rtl direction in WVList

src/core/store.ts
#43 
Disable some code introduced in #165.
=> Fix glitch in reverse infinite scrolling in iOS Safari

src/core/cache.spec.ts, src/core/cache.ts, src/core/scroller.ts, src/core/store.ts
=> Remove premeasureing before imperative scrolling

.size-limit.json, e2e/VList.spec.ts, src/core/environment.ts, src/core/scroller.ts, src/core/types.ts, src/index.ts, src/react/VList.tsx, stories/advanced/Chat.stories.tsx, stories/basics/VList.stories.tsx
#14 
This PR is initial implementation of smooth scrolling.
=> Add smooth option to scrollToIndex

e2e/VList.spec.ts, src/core/cache.spec.ts, src/core/cache.ts, src/core/scroller.ts, src/core/store.ts
=> Improve start response of smooth scrolling

src/core/scroller.ts, src/core/types.ts, src/react/Viewport.tsx, stories/basics/VList.stories.tsx
close #227 
#4 
Add missing features for keyboard navigation.
=> Add `align: nearest` option and onKeydown prop

src/core/scroller.ts, src/core/store.ts
=> Include start padding in calculation of maximum scroll offset

src/core/store.ts, src/react/VGrid.tsx, src/react/VList.spec.tsx, src/react/VList.tsx, src/react/WVList.spec.tsx, src/react/WVList.tsx, src/react/__snapshots__/VGrid.rtl.spec.tsx.snap, src/react/__snapshots__/VGrid.spec.tsx.snap, src/react/__snapshots__/VList.rtl.spec.tsx.snap, src/react/__snapshots__/VList.spec.tsx.snap, src/react/__snapshots__/WVList.rtl.spec.tsx.snap, src/react/__snapshots__/WVList.spec.tsx.snap, stories/basics/WVList.stories.tsx
=> Additional fix for #235

README.md, src/react/VList.spec.tsx, src/react/VList.tsx, src/react/__snapshots__/VList.spec.tsx.snap, stories/basics/VList.stories.tsx
=> Accept render prop as children of VList

src/react/VList.tsx, src/react/WVList.spec.tsx, src/react/WVList.tsx, src/react/__snapshots__/WVList.spec.tsx.snap, src/react/useChildren.ts, src/react/utils.ts
=> Accept render prop as children of WVList

src/react/ListItem.tsx, src/react/VList.spec.tsx, src/react/WVList.spec.tsx, src/react/__snapshots__/VList.spec.tsx.snap, src/react/__snapshots__/WVList.spec.tsx.snap
=> Add index to CustomItemComponentProps

src/react/WVList.tsx, stories/basics/WVList.stories.tsx
closes issue: https://github.com/inokawa/virtua/issues/250
=> add shift functionality for WVList

src/core/store.ts, src/react/WVList.tsx, src/react/__snapshots__/WVList.spec.tsx.snap
closes issue: https://github.com/inokawa/virtua/issues/252
=> remove viewport sizing fallback from WVList

README.md, e2e/VList.spec.ts, e2e/utils.ts, src/core/store.ts
=> Adjust range with unflushed jump

src/core/store.ts
=> Improved detection of artificial scroll caused by jumps

src/core/store.ts
=> Fix flickering caused by race condition with flushSync

e2e/VList.spec.ts, src/core/store.ts
=> Fix bug range can be wrong if scroll doesn't occur after shifting

stories/basics/VList.stories.tsx
=> Add skeleton story

e2e/VList.spec.ts, e2e/utils.ts, src/core/store.ts, src/react/VList.tsx, src/react/WVList.tsx, stories/basics/VList.stories.tsx
=> Refactor logic for reverse mode and update docs

src/core/store.ts, src/react/Virtualizer.tsx, src/react/WindowVirtualizer.tsx
=> Fix swr minify issue in Next.js

src/core/scroller.ts
=> Improve wheel event handling

e2e/VList.spec.ts, src/core/environment.ts, src/core/scroller.ts, src/core/store.ts
=> Refactor scroll normalization and drop RTL support for legacy Chrome

src/core/store.ts
This reverts commit e166a4f2a59f03f5b35198e0c2a6b9447a3d5d26, reversing changes made to ec679a03240be5e6be2197ea7cefb7e84e305136.
=> Revert "Merge pull request #334 from inokawa/refactor-calculate-jump"

.eslintrc.json, .github/ISSUE_TEMPLATE/bug_report.md, .github/workflows/check.yml, .size-limit.json, .storybook/main.js, README.md, package-lock.json, package.json, rollup.config.mjs, src/solid/ListItem.tsx, src/solid/RangedFor.tsx, src/solid/VList.tsx, src/solid/index.ts, src/solid/types.ts, stories/solid/VList.stories.tsx, typedoc.json
=> Add Solid implementation

src/core/scroller.ts
=> Remove waiting for measurement during scrollTo

.size-limit.json, src/solid/VList.tsx, src/solid/Virtualizer.tsx, src/solid/WindowVirtualizer.tsx, src/solid/index.ts, src/solid/utils.ts, stories/solid/WindowVirtualizer.stories.tsx
=> Add Virtualizer and WindowVirtualizer for Solid

e2e/VList.spec.ts, e2e/WindowVirtualizer.spec.ts, src/core/cache.spec.ts, src/core/cache.ts, src/core/scroller.ts, src/core/store.ts
=> Refactor jump calculation

src/core/store.ts
=> Change minimum overscan to 0

.eslintrc.json, package-lock.json, package.json
https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-restricted-paths.md
=> Setup eslint-plugin-import and enable import/no-restricted-paths

stories/react/advanced/Resize and scroll.stories.tsx
This is the storybook PR requested from #380. This example is currently broken in Virtua 0.27.0.
Thank you!
=> Add resize and scroll storybook example

e2e/VList.spec.ts, e2e/utils.ts, src/core/store.ts, stories/react/advanced/Collapse and scroll.stories.tsx, stories/react/basics/VList.stories.tsx
=> Fix regression related to smooth scrolling during resize

src/core/store.ts
=> Recompute range to support  smooth scrolling with resizing

src/vue/Virtualizer.tsx, stories/vue/HeaderAndFooter.vue, stories/vue/Virtualizer.stories.tsx
=> Add startMargin/endMargin prop to Vue Virtualizer

src/core/scroller.ts, src/core/store.ts
=> Refactor startOffset in WindowVirtualizer

src/core/scroller.ts, src/core/store.ts
=> Refactor jump compensation with shift

src/core/store.ts
#315 
also fixes regression by #407
=> Improve jump compensation with shift

src/vue/Virtualizer.tsx, stories/vue/HeaderAndFooter.vue, stories/vue/Nested.vue, stories/vue/Virtualizer.stories.tsx
=> Add scrollRef prop to Vue Virtualizer

stories/react/advanced/Collapse and remove.stories.tsx
=> Add collapse and remove storybook

README.md
=> Update FAQ section

src/react/Virtualizer.tsx
related #431 
Make keepMounted prop immutable.
=> Fix unnecessary mutation to  keepMounted prop

.eslintrc.json, .github/ISSUE_TEMPLATE/bug_report.md, .github/workflows/check.yml, .storybook/main.js, README.md, package-lock.json, package.json, rollup.config.mjs, scripts/rollup-plugin-svelte-copy.mjs, src/core/cache.spec.ts, src/core/cache.ts, src/core/resizer.ts, src/core/scroller.ts, src/core/store.ts, src/svelte/ListItem.svelte, src/svelte/VList.svelte, src/svelte/core.ts, src/svelte/index.ts, src/svelte/utils.ts, stories/svelte/Controls.svelte, stories/svelte/Default.svelte, stories/svelte/Horizontal.svelte, stories/svelte/VList.stories.tsx, tsconfig.json, tsconfig.svelte.json
=> Add Svelte implementation

src/solid/Virtualizer.tsx, stories/solid/Virtualizer.stories.tsx
=> Add scrollRef and startMargin prop to Solid Virtualizer

src/vue/Virtualizer.tsx
=> Fix regression of Vue startMargin

e2e/VList.spec.ts, src/core/store.ts, stories/react/advanced/Collapse.stories.tsx
fix https://github.com/inokawa/virtua/discussions/475
=> Improve jump compensation at end

src/svelte/ListItem.svelte, src/svelte/VList.svelte, src/svelte/utils.ts
=> Fixed bug Svelte VList ignores items resize

README.md, src/vue/VList.spec.ts, src/vue/VList.ssr.spec.ts, src/vue/VList.tsx, src/vue/Virtualizer.tsx, src/vue/WindowVirtualizer.spec.ts, src/vue/WindowVirtualizer.tsx, stories/vue/Controlls.vue, stories/vue/Default.vue, stories/vue/HeaderAndFooter.vue, stories/vue/Horizontal.vue, stories/vue/Nested.vue, stories/vue/TableElement.vue, stories/vue/WindowVirtualizer.vue
=> Pass index to slot of Vue Virtualizer

src/svelte/utils.ts
=> Fix error in Svelte VList caused by importing core

README.md, package-lock.json, package.json, src/svelte/ListItem.svelte, src/svelte/VList.svelte, src/svelte/types.ts, src/svelte/utils.ts, stories/svelte/Controls.svelte, stories/svelte/Default.svelte, stories/svelte/Horizontal.svelte
=> Migrate to Svelte 5

src/svelte/VList.svelte, src/svelte/VList.type.ts, src/svelte/Virtualizer.svelte, src/svelte/Virtualizer.type.ts, src/svelte/index.ts, typedoc.json
=> Generate docs for Svelte

src/svelte/WindowVirtualizer.svelte, src/svelte/WindowVirtualizer.type.ts, src/svelte/core.ts, src/svelte/index.ts, stories/svelte/WindowVirtualizer.stories.tsx, stories/svelte/WindowVirtualizer.svelte
=> Add Svelte WindowVirtualizer

src/core/store.ts, src/react/Virtualizer.tsx, src/react/WindowVirtualizer.tsx, src/solid/Virtualizer.tsx, src/solid/WindowVirtualizer.tsx, src/svelte/VList.svelte, src/svelte/Virtualizer.svelte, src/svelte/Virtualizer.type.ts, src/svelte/WindowVirtualizer.svelte, src/svelte/WindowVirtualizer.type.ts, src/svelte/core.ts, src/vue/VList.tsx, src/vue/Virtualizer.tsx, src/vue/WindowVirtualizer.tsx, stories/react/advanced/Feed.stories.tsx, stories/react/advanced/Sticky Group.stories.tsx, stories/react/basics/VList.stories.tsx, stories/react/basics/Virtualizer.stories.tsx, stories/react/basics/WindowVirtualizer.stories.tsx
Here is the pr for the refactor. When should I run docs? Or is that done after merged?
Tested on my react project, haven't tested others (except running e2e)
=> Refactor startIndex/endIndex to findStartIndex()/findEndIndex()

src/vue/ListItem.tsx, src/vue/Virtualizer.tsx, src/vue/WindowVirtualizer.tsx, src/vue/utils.ts
=> Optimize Vue virtualizer with computed

src/core/store.ts
Fixes https://github.com/inokawa/virtua/issues/552
=> Update the state when new data is added and the scroll is at the bottom

README.md, stories/react/comparisons/comparisons.stories.tsx, stories/react/comparisons/components/common.tsx, stories/react/comparisons/for benchmarks/react-virtual.stories.tsx, stories/react/comparisons/for benchmarks/react-virtualized.stories.tsx, stories/react/comparisons/for benchmarks/react-virtuoso.stories.tsx, stories/react/comparisons/for benchmarks/react-window.stories.tsx, stories/react/comparisons/for benchmarks/virtua.stories.tsx, stories/react/comparisons/index.bench.tsx
=> Add heavy dom item to benchmark

package.json, rollup.config.mjs
=> Expose unstable core

src/core/store.ts
#597 
Revert range clamping behavior while jump flushing, which is  unintendedly dropped in https://github.com/inokawa/virtua/releases/tag/0.37.0 .
=> Fix regression in 0.37.0

src/react/VGrid.tsx
created from discussion https://github.com/inokawa/virtua/discussions/632
=> feat: add onScroll & onScrollEnd props to VGrid

stories/solid/VList.stories.tsx, stories/svelte/Controls.svelte, stories/vue/Controlls.vue
=> Update stories to test prepending

src/solid/ListItem.tsx, src/solid/VList.tsx, src/solid/Virtualizer.tsx, src/solid/index.ts, src/solid/types.ts, stories/solid/advanced/Sticky Group.stories.tsx, stories/solid/basics/VList.stories.tsx, stories/solid/basics/Virtualizer.stories.tsx, stories/solid/basics/WindowVirtualizer.stories.tsx
What's new:
- keepMounted property now works in SolidJS
- item property now works in SolidJS
- Added "Sticky Groups" example for SolidJS (storybook)
=> Add keepMounted= + item= to SolidJS

.gitignore
I think this more friendly for contributors.
While I was doing PR's, I accidentally committed `.idea` several times :D
=> Ignore IDEA/VSCode settings dir

src/react/Virtualizer.tsx
#692 
`as` prop is enough for that purpose.
=> Revert domRef prop of Virtualizer

.storybook/main.js, .storybook/manager.js, .storybook/preview.jsx, package-lock.json, package.json
=> Restore code block in storybook

src/core/scroller.ts, src/core/utils.ts
=> Fix UnhandledPromiseRejection error introduced in 0.43.2

e2e/VList.spec.ts, e2e/WindowVirtualizer.spec.ts, e2e/utils.ts, src/core/scroller.ts, src/core/store.ts
=> Improve smooth scroll accuracy

src/react/Virtualizer.tsx, src/solid/Virtualizer.tsx, src/solid/WindowVirtualizer.tsx, src/vue/VList.tsx, src/vue/Virtualizer.tsx
=> Refactor internals

src/svelte/VList.svelte, src/svelte/VList.type.ts, src/svelte/Virtualizer.svelte, src/svelte/Virtualizer.type.ts, src/svelte/utils.ts
=> Implement keepMounted prop for Svelte
